# This file was generated by GoReleaser. DO NOT EDIT.
cask "mmdb-cli" do
  version "0.16.0"

  on_macos do
    on_intel do
      sha256 "9e162134e1f1faa9eb6f4c39769269accbf768a47345c3245d818f9e82ff594f"
      url "https://github.com/InfraZ/mmdb-cli/releases/download/v#{version}/mmdb-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0f9afd36ce8f3869bf9b28c56c01ee681c22e6fe199aa2c42c0726890a03f073"
      url "https://github.com/InfraZ/mmdb-cli/releases/download/v#{version}/mmdb-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9be169cb618c0504751e0a06cf5083d3a76547612d6d1170604712e752d76182"
      url "https://github.com/InfraZ/mmdb-cli/releases/download/v#{version}/mmdb-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0c9f76b5920812812eaae28bf4c037d9683344d3ae406cee92a1ee8c72bcef53"
      url "https://github.com/InfraZ/mmdb-cli/releases/download/v#{version}/mmdb-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "mmdb-cli"
  desc "InfraZ MMDB-CLI is a command-line toolkit to work with MMDB files.
It empowers you to create, transform, export, and explore MMDB files.
"
  homepage "https://infraz.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mmdb-cli"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mmdb-cli"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    mmdb-cli is not notarized by Apple. If macOS blocks the binary,
    run: xattr -dr com.apple.quarantine $(which mmdb-cli)
  EOS
end
