# This file was generated by GoReleaser. DO NOT EDIT.
cask "mmdb-cli" do
  version "0.17.0"

  on_macos do
    on_arm do
      sha256 "293b638288a19050e8cc52a743bc39b050048ae7c127e1a9250cffa5ded10385"
      url "https://github.com/InfraZ/mmdb-cli/releases/download/v#{version}/mmdb-cli_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0197a13fa3fdae236624da8f8735d88aba0762f70134bae71fd6aa90207a84a3"
      url "https://github.com/InfraZ/mmdb-cli/releases/download/v#{version}/mmdb-cli_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f3b588d66e5f5cecf62d86507d4d500338f5a5111b9abae15bcea3f171df66a6"
      url "https://github.com/InfraZ/mmdb-cli/releases/download/v#{version}/mmdb-cli_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f0625a01c27857e14c1c916de0f65abc6d29192fe890c320597b68022297fb74"
      url "https://github.com/InfraZ/mmdb-cli/releases/download/v#{version}/mmdb-cli_#{version}_linux_amd64.tar.gz"
    end
  end

  name "mmdb-cli"
  desc "InfraZ MMDB-CLI is a command-line toolkit to work with MMDB files.
It empowers you to create, transform, export, and explore MMDB files.
"
  homepage "https://infraz.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mmdb-cli"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mmdb-cli"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    mmdb-cli is not notarized by Apple. If macOS blocks the binary,
    run: xattr -dr com.apple.quarantine $(which mmdb-cli)
  EOS
end
