# This file was generated by GoReleaser. DO NOT EDIT.
cask "mmdb-cli" do
  version "0.15.3"

  on_macos do
    on_intel do
      sha256 "de0076f5d319c275e7e705a120dea3d0d6e0d4de8de4f5768006fcc920a49ea5"
      url "https://github.com/InfraZ/mmdb-cli/releases/download/v#{version}/mmdb-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "97c169664b8b23affa9b6d44024ed698bd06cd1ba2ae970936c6ab10625bc4e1"
      url "https://github.com/InfraZ/mmdb-cli/releases/download/v#{version}/mmdb-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "620a1e512277d15593d7e99ac516fa4a4238071d60c6ae55d687ee55ac7393bd"
      url "https://github.com/InfraZ/mmdb-cli/releases/download/v#{version}/mmdb-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "305f5e437846b49a63c9a72a5898fab51e825962df309fe5b49a2338e1a44e8d"
      url "https://github.com/InfraZ/mmdb-cli/releases/download/v#{version}/mmdb-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "mmdb-cli"
  desc "InfraZ MMDB-CLI is a command-line toolkit to work with MMDB files.
It empowers you to create, transform, export, and explore MMDB files.
"
  homepage "https://infraz.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mmdb-cli"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mmdb-cli"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    mmdb-cli is not notarized by Apple. If macOS blocks the binary,
    run: xattr -dr com.apple.quarantine $(which mmdb-cli)
  EOS
end
