# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MmdbCli < Formula
  desc "InfraZ MMDB-CLI is a command-line toolkit to work with MMDB files.
It empowers you to create, transform, export, and explore MMDB files.
"
  homepage "https://infraz.io"
  version "0.15.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/InfraZ/mmdb-cli/releases/download/v0.15.1/mmdb-cli_0.15.1_darwin_amd64.tar.gz"
      sha256 "ef6593c722c93a0e9da53d6fb3796835209d0c31eb12b3a76f5a8e54be8aa2dc"

      define_method(:install) do
        bin.install "mmdb-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/InfraZ/mmdb-cli/releases/download/v0.15.1/mmdb-cli_0.15.1_darwin_arm64.tar.gz"
      sha256 "3efe8500b2560378692716ef331efc68aa4fee9f9443390188c0a69cc1be7a2e"

      define_method(:install) do
        bin.install "mmdb-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/InfraZ/mmdb-cli/releases/download/v0.15.1/mmdb-cli_0.15.1_linux_amd64.tar.gz"
      sha256 "ee5e9d21f3f37a4619f47be23197510598779f1d11aafeec29dec949a58e0bc5"
      define_method(:install) do
        bin.install "mmdb-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/InfraZ/mmdb-cli/releases/download/v0.15.1/mmdb-cli_0.15.1_linux_arm64.tar.gz"
      sha256 "6623e7e706903b5f9769586cef4b2465f729d258e4fcb5f316442925f08d71f2"
      define_method(:install) do
        bin.install "mmdb-cli"
      end
    end
  end
end
