# This file was generated by GoReleaser. DO NOT EDIT.
cask "mmdb-cli" do
  version "0.15.0"

  on_macos do
    on_intel do
      sha256 "162c50539a1d9bcf4d8b02810c243747425fdd88b164ce5d32dc7a1c8d959652"
      url "https://github.com/InfraZ/mmdb-cli/releases/download/v#{version}/mmdb-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "fedde041f4a1bde4fc7801ddaf1839d847ae1afd7c5e94cda64680b493642f34"
      url "https://github.com/InfraZ/mmdb-cli/releases/download/v#{version}/mmdb-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "dae10ca44c4e8339c5759cf0f5c460069f24e1d1ed78c08d85ccb1302e55084b"
      url "https://github.com/InfraZ/mmdb-cli/releases/download/v#{version}/mmdb-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ae094d39e42d078e87d295c6c8efdc6b19ef334694bb23e2659a6669a2ec28d1"
      url "https://github.com/InfraZ/mmdb-cli/releases/download/v#{version}/mmdb-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "mmdb-cli"
  desc "InfraZ MMDB-CLI is a command-line toolkit to work with MMDB files.
It empowers you to create, transform, export, and explore MMDB files.
"
  homepage "https://infraz.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mmdb-cli"
  generate_completions_from_executable "mmdb-cli",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mmdb-cli"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    mmdb-cli is not notarized by Apple. If macOS blocks the binary,
    run: xattr -dr com.apple.quarantine $(which mmdb-cli)
  EOS
end
